apiVersion: v1
kind: Secret
metadata:
  name: {{ include "desme-audio.fullname" . }}-secrets
  labels:
    {{- include "desme-audio.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
